### PR TITLE
cleaning up CLI

### PR DESCRIPTION
**Pull request by bollwyvl**
For https://github.com/Anaconda-Server/anaconda-notebook/issues/41

This adds an `nbbrowserpdf` command `entry_point`, and refines the behavior with streams, etc.

### CODE REVIEW

**Comment by ijstokes** [comment]
@bollwyvl this looks pretty good.  Anything holding up a merge of this PR? I'm testing it now.

**Comment by bollwyvl** [comment]
It's good to go... i was going to get at least some tests in there, but
they can wait.

**Comment by ijstokes** [comment]
Issues:

* One page only (some content not present)
* Weird page size (elongated)

See attached PDF (below)

I created a Linux environment to test this in by doing:

```bash
conda create -n nbpdf35 -c ijstokes nbbrowserpdf
```

The `nbbrowserpdf` package came from my Anaconda Cloud channel and was created using:

```bash
conda build conda.recipe
```

from the PR branch.  Nothing was included in my test environment other than `nbbrowserpdf` conda package (my build of it from the PR) and its dependencies.  I will note that `nbpresent` was **not** one of the packages installed.

[Examples.pdf](https://files.zenhub.io/566721f00ccbf2c2061a7d2b)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by bollwyvl** [comment]
> - One page only (some content not present)
> - Weird page size (elongated)

Again, it was originally written for nbpresent, which does screen-at-a-time shots. I can't use `print_`, which would fire the webkit printer stuff which drops backgrounds, etc, so I need to figure out a way to either:
- render the whole page as i am doingand slice the big pdf after the fact (pypdf might have my back on this)
- figure out the screen size/output size relationship more precisely (dpi, etc.) and figure out how to grab just enough of each region

As to the content not showing, it may be a timing thing.

ANYHOW... these pre-existing issues, not affected by the CLI work.

**Comment by ijstokes** [comment]
But this is the notebook from `nbpresent/notebooks/Examples.ipynb` so I thought this contained the `nbpresent` meta-data.  Do I need to use `nbbrowserpdf` in a different way to get the content slideshow PDF from the notebook file?

**Comment by bollwyvl** [comment]
> But this is the notebook from nbpresent/notebooks/Examples.ipynb so I thought this contained the nbpresent meta-data. Do I need to use nbbrowserpdf in a different way to get the content slideshow PDF from the notebook file?

nbbrowserpdf doesn't know anything about slides, and could be used as the baseline for other types of browser-based pdf output... i dunno, invoices, posters, form letters.

When nbpresent is installed AND nbbrowserpdf is installed, then you can 
```shell
nbpresent -i notebooks/README.ipynb -f pdf -o README.pdf
```

It could be we need a metapackage, `nbpresent-pdf`, that depends on `nbbrowserpdf` and `nbpresent`.

**Comment by ijstokes** [comment]
OK, I get it.  I'll add some issues to track what I think needs to be done as "next steps" for this, but the `cli-work` PR certainly seems GTG, so I'd say "merge it"

**Pull request merged**
